# TP1 : Premiers pas avec Python

Le but du TP est de commencer à étudier de vraies données avec Python. Pour plus de détails sur Python, NumPy et Matplotlib, un grand nombre de ressources sont disponibles sur https://pythonprogramming.net/ , y compris plusieurs séries de vidéos YouTube.

La documentation complète est disponible ici : 
https://docs.scipy.org/doc/numpy-1.15.0/reference/index.html

# Initiation à Numpy

Python est un langage très complet et utilisé dans de nombreux domaines, du développement Web à la robotique.

Dans cette série de TP, nous l'utiliserons pour le calcul mathématique et la  science des données.

Les bibliothèques de prédilection pour le calcul mathématique en Python sont NumPy et Matplotlib. Pour nous familiariser avec ces bibliothèques, nous allons nous baser sur le tutoriel disponible ici : https://numpy.org/doc/stable/user/absolute_beginners.html.

La plupart sinon toutes les réponses aux questions du TP sont disponibles dans ce tutoriel.


## Ex. 1 : Python et NumPy en quelques lignes
Commencez par importer la bibliothèque numpy afin de pouvoir l'utiliser

In [2]:
import numpy as np

Calculez $\log(\cos(1-(1+1)/2))$ avec NumPy

In [3]:
print("log(cos(1−(1+1)/2)) = ", np.log(np.cos(1 - (1+1) / 2)))

log(cos(1−(1+1)/2)) =  0.0


Créez une variable `a` à laquelle vous affecterez le résultat du calcul $2*(3+ 2)$. Puis enlevez $1$ à la valeur de la variable `a`.

In [4]:
a = 2 * (3 + 1)
print(a)

a-=1
print(a)

8
7


En NumPy, les matrices et vecteurs sont representés par des variables de type np.array, dont le nombre de dimensions peut varier.

Construisez un vecteur $v = (1, 2, −1, −2, 0, 5)$
Vérifiez la taille et forme de ce vecteurs.

In [5]:
v = np.array([1,2,-1,-2,0,5])
print(v)

[ 1  2 -1 -2  0  5]


En mathématiques, il est important de distinguer les vecteurs colonnes des vecteurs lignes. Calculez un vecteur u correspondant à la version vecteur colonne de $v$. De même, construisez $w = u^\top$. Essayez de le faire de plusieurs manières différentes afin de commencez à maitriser Numpy.

In [6]:
u = v.reshape((-1, 1))
print(u)

## 𝑤 = 𝑢⊤
w = v.T
print(w)

[[ 1]
 [ 2]
 [-1]
 [-2]
 [ 0]
 [ 5]]
[ 1  2 -1 -2  0  5]


Calculez le vecteur de la différence $u^t − w$ (et vérifiez que $u = W^
t$). Quelle est la nature mathématique de cet objet ? Essayez de calculer $u−w$. Pourquoi obtient-on cet objet ?

In [7]:
UTmoinsW = u.T - w ## vecteur nul (contenant uniquement des zéros)
print(UTmoinsW)

print(np.array_equal(u, w.T))
    
print(u-w) ## matrice car u et w les dimensions ne sont pas compatibles 

[[0 0 0 0 0 0]]
False
[[ 0 -1  2  3  1 -4]
 [ 1  0  3  4  2 -3]
 [-2 -3  0  1 -1 -6]
 [-3 -4 -1  0 -2 -7]
 [-1 -2  1  2  0 -5]
 [ 4  3  6  7  5  0]]


7. Extrayez la valeur de la deuxième composante des vecteur $u$ et $w$. Affectez à la variable $b$ la valeur de la dernière composante du vecteur $u$. Affectez à la variable $n$ la taille du vecteur $u$ (car $u \in \mathbb{R}^n$)

In [11]:
print(u)
print(v)

a1 = u[1]
a2 = w[1]

n = len(u)
b = u[n-1]

print(a1 ,a2)
print(b)
print(n)


[[ 1]
 [ 2]
 [-1]
 [-2]
 [ 0]
 [ 5]]
[ 1  2 -1 -2  0  5]
[2] 2
[5]
6


Créez un vecteur $x = (v(0), v(5), v(2))$. Calculez la somme des éléments de $x$. (en cas de doute sur la nature d’une fonction, faites `help(np.sum)`)

Créez un vecteur $y = (v(1), . . . , v(4))$, un vecteur d’indice allant de 0 à 3.

Calculez la somme cumulée des éléments du vecteur $u$. Quelle est la taille de cet object ? Affectez le résultat de ce calcul à une nouvelle variable $c$. Que signifie RTFM ?

Créez un nouveau vecteur $t = (1, 1, 1, 0, 0, −1, −1, 1, 1, 1)$. Que fait l’instruction diff(t)? (Si vous n’avez pas fait `help(diff)` c’est que quelque chose vous échappe)

Calculez les modalités de t dans une variable m.

Que fait l’instruction t==m[0] ? Comptez les effectifs de chaque modalité de t


Refaire la même chose avec une boucle en utilisant l’instruction for. vérifiez que les résultats sont bien les mêmes.

Créez la matrice
$A = \begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
−1 & 0 & 1\\
1 & 1 & 2
\end{pmatrix}$

Quelle est la deuxième colonne de A ? Créez un vecteur s composé de la troisième ligne de A.

Créer un vecteur contenant 60 valeurs également réparties croissantes dans l'intervalle $[0, 2\pi]$  Que fait l’instructions plt.plot(t). Expliquez la différence entre plt.plot(a) et plt.plot(a,b).

# Conclusion

Pour conclure ce TP d'introduction à Numpy, suivez bien l'ensemble du tutoriel présenté au début : https://numpy.org/doc/stable/user/absolute_beginners.html
Pour aller plus loin : 
- https://numpy.org/doc/stable/user/basics.html
- Des exercices : https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
- et encore plus loin : https://www.labri.fr/perso/nrougier/from-python-to-numpy/